// ─────────────────────────────────────────────────────────────────────────────
// Nebula Presets
// Configuration instances for different nebula environments.
// ─────────────────────────────────────────────────────────────────────────────
import type { NebulaPresetConfig, NebulaPresetId } from './nebula-types';

export const NEBULA_PRESETS: Record<NebulaPresetId, NebulaPresetConfig> = {
  'deep-space': {
    id: 'deep-space',
    density: 1.0,
    opacity: 1.0,
    speedBase: 1.0,
    scaleBase: 1.0,
    brightness: 1.0,
    contrast: 1.0,
    saturation: 1.0,
    layers: {
      ultra: [
        {
          id: 'bg',
          primaryColor: '#580bb5',
          secondaryColor: '#2b0559',
          radius: 480,
          opacity: 0.45,
          scale: 0.003,
          speed: 0.015,
          octaves: 4,
        },
        {
          id: 'mid',
          primaryColor: '#ff6a00',
          secondaryColor: '#803500',
          radius: 465,
          opacity: 0.25,
          scale: 0.005,
          speed: 0.025,
          octaves: 3,
        },
        {
          id: 'fg',
          primaryColor: '#00e5e5',
          secondaryColor: '#007373',
          radius: 450,
          opacity: 0.15,
          scale: 0.008,
          speed: 0.035,
          octaves: 3,
        },
      ],
      high: [
        {
          id: 'bg',
          primaryColor: '#580bb5',
          secondaryColor: '#2b0559',
          radius: 480,
          opacity: 0.4,
          scale: 0.003,
          speed: 0.015,
          octaves: 3,
        },
        {
          id: 'mid',
          primaryColor: '#ff6a00',
          secondaryColor: '#803500',
          radius: 465,
          opacity: 0.2,
          scale: 0.005,
          speed: 0.02,
          octaves: 3,
        },
        {
          id: 'fg',
          primaryColor: '#00e5e5',
          secondaryColor: '#007373',
          radius: 450,
          opacity: 0.1,
          scale: 0.008,
          speed: 0.03,
          octaves: 2,
        },
      ],
      medium: [
        {
          id: 'bg',
          primaryColor: '#580bb5',
          secondaryColor: '#2b0559',
          radius: 480,
          opacity: 0.35,
          scale: 0.003,
          speed: 0.012,
          octaves: 2,
        },
        {
          id: 'mid',
          primaryColor: '#ff6a00',
          secondaryColor: '#803500',
          radius: 465,
          opacity: 0.15,
          scale: 0.005,
          speed: 0.018,
          octaves: 2,
        },
      ],
      low: [
        {
          id: 'bg',
          primaryColor: '#580bb5',
          secondaryColor: '#2b0559',
          radius: 480,
          opacity: 0.3,
          scale: 0.002,
          speed: 0.008,
          octaves: 1,
        },
      ],
    },
  },
  'blue-nebula': {
    id: 'blue-nebula',
    density: 1.2,
    opacity: 0.9,
    speedBase: 0.8,
    scaleBase: 1.1,
    brightness: 1.1,
    contrast: 1.1,
    saturation: 1.2,
    layers: {
      ultra: [
        {
          id: 'bg',
          primaryColor: '#09235e',
          secondaryColor: '#030c24',
          radius: 480,
          opacity: 0.5,
          scale: 0.0025,
          speed: 0.01,
          octaves: 4,
        },
        {
          id: 'mid',
          primaryColor: '#2062cc',
          secondaryColor: '#103166',
          radius: 460,
          opacity: 0.4,
          scale: 0.004,
          speed: 0.02,
          octaves: 3,
        },
        {
          id: 'fg',
          primaryColor: '#7aabff',
          secondaryColor: '#3d5580',
          radius: 440,
          opacity: 0.2,
          scale: 0.007,
          speed: 0.03,
          octaves: 3,
        },
      ],
      high: [
        {
          id: 'bg',
          primaryColor: '#09235e',
          secondaryColor: '#030c24',
          radius: 480,
          opacity: 0.45,
          scale: 0.0025,
          speed: 0.01,
          octaves: 3,
        },
        {
          id: 'mid',
          primaryColor: '#2062cc',
          secondaryColor: '#103166',
          radius: 460,
          opacity: 0.35,
          scale: 0.004,
          speed: 0.02,
          octaves: 3,
        },
        {
          id: 'fg',
          primaryColor: '#7aabff',
          secondaryColor: '#3d5580',
          radius: 440,
          opacity: 0.15,
          scale: 0.007,
          speed: 0.03,
          octaves: 2,
        },
      ],
      medium: [
        {
          id: 'bg',
          primaryColor: '#09235e',
          secondaryColor: '#030c24',
          radius: 480,
          opacity: 0.4,
          scale: 0.0025,
          speed: 0.01,
          octaves: 2,
        },
        {
          id: 'mid',
          primaryColor: '#2062cc',
          secondaryColor: '#103166',
          radius: 460,
          opacity: 0.3,
          scale: 0.004,
          speed: 0.015,
          octaves: 2,
        },
      ],
      low: [
        {
          id: 'bg',
          primaryColor: '#09235e',
          secondaryColor: '#030c24',
          radius: 480,
          opacity: 0.35,
          scale: 0.0025,
          speed: 0.008,
          octaves: 1,
        },
      ],
    },
  },
  'purple-nebula': {
    id: 'purple-nebula',
    density: 1.5,
    opacity: 0.8,
    speedBase: 0.9,
    scaleBase: 1.2,
    brightness: 1.0,
    contrast: 1.2,
    saturation: 1.3,
    layers: {
      ultra: [
        {
          id: 'bg',
          primaryColor: '#2b0933',
          secondaryColor: '#100314',
          radius: 480,
          opacity: 0.6,
          scale: 0.003,
          speed: 0.012,
          octaves: 4,
        },
        {
          id: 'mid',
          primaryColor: '#7b1ca1',
          secondaryColor: '#3d0e50',
          radius: 460,
          opacity: 0.35,
          scale: 0.005,
          speed: 0.022,
          octaves: 3,
        },
        {
          id: 'fg',
          primaryColor: '#d266fc',
          secondaryColor: '#69337e',
          radius: 440,
          opacity: 0.15,
          scale: 0.008,
          speed: 0.035,
          octaves: 3,
        },
      ],
      high: [
        {
          id: 'bg',
          primaryColor: '#2b0933',
          secondaryColor: '#100314',
          radius: 480,
          opacity: 0.5,
          scale: 0.003,
          speed: 0.012,
          octaves: 3,
        },
        {
          id: 'mid',
          primaryColor: '#7b1ca1',
          secondaryColor: '#3d0e50',
          radius: 460,
          opacity: 0.3,
          scale: 0.005,
          speed: 0.022,
          octaves: 3,
        },
        {
          id: 'fg',
          primaryColor: '#d266fc',
          secondaryColor: '#69337e',
          radius: 440,
          opacity: 0.1,
          scale: 0.008,
          speed: 0.035,
          octaves: 2,
        },
      ],
      medium: [
        {
          id: 'bg',
          primaryColor: '#2b0933',
          secondaryColor: '#100314',
          radius: 480,
          opacity: 0.45,
          scale: 0.003,
          speed: 0.01,
          octaves: 2,
        },
        {
          id: 'mid',
          primaryColor: '#7b1ca1',
          secondaryColor: '#3d0e50',
          radius: 460,
          opacity: 0.25,
          scale: 0.005,
          speed: 0.018,
          octaves: 2,
        },
      ],
      low: [
        {
          id: 'bg',
          primaryColor: '#2b0933',
          secondaryColor: '#100314',
          radius: 480,
          opacity: 0.4,
          scale: 0.0025,
          speed: 0.008,
          octaves: 1,
        },
      ],
    },
  },
  'golden-nebula': {
    id: 'golden-nebula',
    density: 1.1,
    opacity: 1.0,
    speedBase: 1.0,
    scaleBase: 1.0,
    brightness: 1.2,
    contrast: 1.0,
    saturation: 1.0,
    layers: {
      ultra: [
        {
          id: 'bg',
          primaryColor: '#4d2e00',
          secondaryColor: '#261700',
          radius: 480,
          opacity: 0.4,
          scale: 0.0028,
          speed: 0.014,
          octaves: 4,
        },
        {
          id: 'mid',
          primaryColor: '#cc8500',
          secondaryColor: '#664200',
          radius: 460,
          opacity: 0.3,
          scale: 0.0045,
          speed: 0.024,
          octaves: 3,
        },
        {
          id: 'fg',
          primaryColor: '#ffdb4d',
          secondaryColor: '#806d26',
          radius: 440,
          opacity: 0.15,
          scale: 0.0075,
          speed: 0.034,
          octaves: 3,
        },
      ],
      high: [
        {
          id: 'bg',
          primaryColor: '#4d2e00',
          secondaryColor: '#261700',
          radius: 480,
          opacity: 0.35,
          scale: 0.0028,
          speed: 0.014,
          octaves: 3,
        },
        {
          id: 'mid',
          primaryColor: '#cc8500',
          secondaryColor: '#664200',
          radius: 460,
          opacity: 0.25,
          scale: 0.0045,
          speed: 0.024,
          octaves: 3,
        },
        {
          id: 'fg',
          primaryColor: '#ffdb4d',
          secondaryColor: '#806d26',
          radius: 440,
          opacity: 0.1,
          scale: 0.0075,
          speed: 0.034,
          octaves: 2,
        },
      ],
      medium: [
        {
          id: 'bg',
          primaryColor: '#4d2e00',
          secondaryColor: '#261700',
          radius: 480,
          opacity: 0.3,
          scale: 0.0028,
          speed: 0.012,
          octaves: 2,
        },
        {
          id: 'mid',
          primaryColor: '#cc8500',
          secondaryColor: '#664200',
          radius: 460,
          opacity: 0.2,
          scale: 0.0045,
          speed: 0.018,
          octaves: 2,
        },
      ],
      low: [
        {
          id: 'bg',
          primaryColor: '#4d2e00',
          secondaryColor: '#261700',
          radius: 480,
          opacity: 0.25,
          scale: 0.0028,
          speed: 0.008,
          octaves: 1,
        },
      ],
    },
  },
  'minimal-space': {
    id: 'minimal-space',
    density: 0.5,
    opacity: 0.5,
    speedBase: 0.5,
    scaleBase: 0.8,
    brightness: 0.8,
    contrast: 1.0,
    saturation: 0.5,
    layers: {
      ultra: [
        {
          id: 'bg',
          primaryColor: '#1a1a2e',
          secondaryColor: '#0d0d17',
          radius: 480,
          opacity: 0.2,
          scale: 0.002,
          speed: 0.005,
          octaves: 2,
        },
      ],
      high: [
        {
          id: 'bg',
          primaryColor: '#1a1a2e',
          secondaryColor: '#0d0d17',
          radius: 480,
          opacity: 0.15,
          scale: 0.002,
          speed: 0.005,
          octaves: 2,
        },
      ],
      medium: [
        {
          id: 'bg',
          primaryColor: '#1a1a2e',
          secondaryColor: '#0d0d17',
          radius: 480,
          opacity: 0.1,
          scale: 0.002,
          speed: 0.004,
          octaves: 1,
        },
      ],
      low: [
        {
          id: 'bg',
          primaryColor: '#1a1a2e',
          secondaryColor: '#0d0d17',
          radius: 480,
          opacity: 0.1,
          scale: 0.002,
          speed: 0.004,
          octaves: 1,
        },
      ],
    },
  },
};
