// ─────────────────────────────────────────────────────────────────────────────
// Starfield Presets
// Configuration instances for different starfield environments.
// ─────────────────────────────────────────────────────────────────────────────
import type { StarfieldPresetConfig, StarfieldPresetId } from './starfield-types';

export const STARFIELD_PRESETS: Record<StarfieldPresetId, StarfieldPresetConfig> = {
  realistic: {
    id: 'realistic',
    densityBase: 1.0,
    opacityBase: 1.0,
    sizeBase: 1.0,
    twinkleSpeedBase: 1.0,
    parallaxStrength: 1.0,
    layers: {
      ultra: [
        {
          id: 'background',
          count: 15000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.3, 0.8],
          brightnessRange: [0.1, 0.4],
          colorTemperatureRange: [4000, 9000],
          seed: 42,
        },
        {
          id: 'midfield',
          count: 8000,
          radiusInner: 200,
          radiusOuter: 400,
          sizeRange: [0.6, 1.5],
          brightnessRange: [0.3, 0.7],
          colorTemperatureRange: [3500, 12000],
          seed: 137,
        },
        {
          id: 'foreground',
          count: 2000,
          radiusInner: 80,
          radiusOuter: 200,
          sizeRange: [1.0, 3.0],
          brightnessRange: [0.5, 1.0],
          colorTemperatureRange: [3000, 15000],
          seed: 256,
        },
      ],
      high: [
        {
          id: 'background',
          count: 10000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.3, 0.8],
          brightnessRange: [0.1, 0.4],
          colorTemperatureRange: [4000, 9000],
          seed: 42,
        },
        {
          id: 'midfield',
          count: 6000,
          radiusInner: 200,
          radiusOuter: 400,
          sizeRange: [0.6, 1.5],
          brightnessRange: [0.3, 0.7],
          colorTemperatureRange: [3500, 12000],
          seed: 137,
        },
        {
          id: 'foreground',
          count: 2000,
          radiusInner: 80,
          radiusOuter: 200,
          sizeRange: [1.0, 3.0],
          brightnessRange: [0.5, 1.0],
          colorTemperatureRange: [3000, 15000],
          seed: 256,
        },
      ],
      medium: [
        {
          id: 'background',
          count: 5000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.4, 0.9],
          brightnessRange: [0.15, 0.45],
          colorTemperatureRange: [4500, 8500],
          seed: 42,
        },
        {
          id: 'midfield',
          count: 2500,
          radiusInner: 200,
          radiusOuter: 400,
          sizeRange: [0.7, 1.6],
          brightnessRange: [0.35, 0.75],
          colorTemperatureRange: [4000, 11000],
          seed: 137,
        },
        {
          id: 'foreground',
          count: 500,
          radiusInner: 80,
          radiusOuter: 200,
          sizeRange: [1.2, 3.0],
          brightnessRange: [0.5, 1.0],
          colorTemperatureRange: [3500, 13000],
          seed: 256,
        },
      ],
      low: [
        {
          id: 'background',
          count: 2000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.5, 1.0],
          brightnessRange: [0.2, 0.5],
          colorTemperatureRange: [5000, 8000],
          seed: 42,
        },
        {
          id: 'midfield',
          count: 800,
          radiusInner: 200,
          radiusOuter: 400,
          sizeRange: [0.8, 1.8],
          brightnessRange: [0.4, 0.8],
          colorTemperatureRange: [4500, 10000],
          seed: 137,
        },
        {
          id: 'foreground',
          count: 200,
          radiusInner: 80,
          radiusOuter: 200,
          sizeRange: [1.5, 3.5],
          brightnessRange: [0.6, 1.0],
          colorTemperatureRange: [4000, 12000],
          seed: 256,
        },
      ],
    },
  },
  'ultra-dense': {
    id: 'ultra-dense',
    densityBase: 2.0,
    opacityBase: 1.0,
    sizeBase: 1.0,
    twinkleSpeedBase: 1.2,
    parallaxStrength: 1.0,
    layers: {
      ultra: [
        {
          id: 'background',
          count: 30000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.3, 0.8],
          brightnessRange: [0.1, 0.4],
          colorTemperatureRange: [4000, 9000],
          seed: 42,
        },
        {
          id: 'midfield',
          count: 15000,
          radiusInner: 200,
          radiusOuter: 400,
          sizeRange: [0.6, 1.5],
          brightnessRange: [0.3, 0.7],
          colorTemperatureRange: [3500, 12000],
          seed: 137,
        },
        {
          id: 'foreground',
          count: 4000,
          radiusInner: 80,
          radiusOuter: 200,
          sizeRange: [1.0, 3.0],
          brightnessRange: [0.5, 1.0],
          colorTemperatureRange: [3000, 15000],
          seed: 256,
        },
      ],
      high: [
        {
          id: 'background',
          count: 20000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.3, 0.8],
          brightnessRange: [0.1, 0.4],
          colorTemperatureRange: [4000, 9000],
          seed: 42,
        },
        {
          id: 'midfield',
          count: 10000,
          radiusInner: 200,
          radiusOuter: 400,
          sizeRange: [0.6, 1.5],
          brightnessRange: [0.3, 0.7],
          colorTemperatureRange: [3500, 12000],
          seed: 137,
        },
        {
          id: 'foreground',
          count: 3000,
          radiusInner: 80,
          radiusOuter: 200,
          sizeRange: [1.0, 3.0],
          brightnessRange: [0.5, 1.0],
          colorTemperatureRange: [3000, 15000],
          seed: 256,
        },
      ],
      medium: [
        {
          id: 'background',
          count: 10000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.4, 0.9],
          brightnessRange: [0.15, 0.45],
          colorTemperatureRange: [4500, 8500],
          seed: 42,
        },
        {
          id: 'midfield',
          count: 5000,
          radiusInner: 200,
          radiusOuter: 400,
          sizeRange: [0.7, 1.6],
          brightnessRange: [0.35, 0.75],
          colorTemperatureRange: [4000, 11000],
          seed: 137,
        },
      ],
      low: [
        {
          id: 'background',
          count: 4000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.5, 1.0],
          brightnessRange: [0.2, 0.5],
          colorTemperatureRange: [5000, 8000],
          seed: 42,
        },
        {
          id: 'midfield',
          count: 2000,
          radiusInner: 200,
          radiusOuter: 400,
          sizeRange: [0.8, 1.8],
          brightnessRange: [0.4, 0.8],
          colorTemperatureRange: [4500, 10000],
          seed: 137,
        },
      ],
    },
  },
  sparse: {
    id: 'sparse',
    densityBase: 0.5,
    opacityBase: 0.8,
    sizeBase: 0.8,
    twinkleSpeedBase: 0.5,
    parallaxStrength: 1.0,
    layers: {
      ultra: [
        {
          id: 'background',
          count: 5000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.2, 0.6],
          brightnessRange: [0.1, 0.3],
          colorTemperatureRange: [4000, 9000],
          seed: 42,
        },
        {
          id: 'foreground',
          count: 1000,
          radiusInner: 150,
          radiusOuter: 300,
          sizeRange: [0.8, 2.0],
          brightnessRange: [0.4, 0.8],
          colorTemperatureRange: [3000, 15000],
          seed: 256,
        },
      ],
      high: [
        {
          id: 'background',
          count: 3000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.2, 0.6],
          brightnessRange: [0.1, 0.3],
          colorTemperatureRange: [4000, 9000],
          seed: 42,
        },
        {
          id: 'foreground',
          count: 800,
          radiusInner: 150,
          radiusOuter: 300,
          sizeRange: [0.8, 2.0],
          brightnessRange: [0.4, 0.8],
          colorTemperatureRange: [3000, 15000],
          seed: 256,
        },
      ],
      medium: [
        {
          id: 'background',
          count: 1500,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.3, 0.7],
          brightnessRange: [0.1, 0.35],
          colorTemperatureRange: [4500, 8500],
          seed: 42,
        },
      ],
      low: [
        {
          id: 'background',
          count: 800,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.4, 0.8],
          brightnessRange: [0.2, 0.4],
          colorTemperatureRange: [5000, 8000],
          seed: 42,
        },
      ],
    },
  },
  'deep-space': {
    id: 'deep-space',
    densityBase: 1.0,
    opacityBase: 1.0,
    sizeBase: 1.0,
    twinkleSpeedBase: 0.8,
    parallaxStrength: 1.5,
    layers: {
      ultra: [
        {
          id: 'deep-space',
          count: 20000,
          radiusInner: 600,
          radiusOuter: 1000,
          sizeRange: [0.2, 0.5],
          brightnessRange: [0.05, 0.3],
          colorTemperatureRange: [4000, 12000],
          seed: 100,
        },
        {
          id: 'background',
          count: 10000,
          radiusInner: 400,
          radiusOuter: 600,
          sizeRange: [0.4, 0.9],
          brightnessRange: [0.2, 0.5],
          colorTemperatureRange: [3500, 10000],
          seed: 42,
        },
        {
          id: 'foreground',
          count: 1500,
          radiusInner: 100,
          radiusOuter: 300,
          sizeRange: [1.2, 2.5],
          brightnessRange: [0.4, 1.0],
          colorTemperatureRange: [3000, 15000],
          seed: 256,
        },
      ],
      high: [
        {
          id: 'deep-space',
          count: 15000,
          radiusInner: 600,
          radiusOuter: 1000,
          sizeRange: [0.2, 0.5],
          brightnessRange: [0.05, 0.3],
          colorTemperatureRange: [4000, 12000],
          seed: 100,
        },
        {
          id: 'background',
          count: 8000,
          radiusInner: 400,
          radiusOuter: 600,
          sizeRange: [0.4, 0.9],
          brightnessRange: [0.2, 0.5],
          colorTemperatureRange: [3500, 10000],
          seed: 42,
        },
        {
          id: 'foreground',
          count: 1000,
          radiusInner: 100,
          radiusOuter: 300,
          sizeRange: [1.2, 2.5],
          brightnessRange: [0.4, 1.0],
          colorTemperatureRange: [3000, 15000],
          seed: 256,
        },
      ],
      medium: [
        {
          id: 'deep-space',
          count: 8000,
          radiusInner: 600,
          radiusOuter: 1000,
          sizeRange: [0.2, 0.5],
          brightnessRange: [0.05, 0.3],
          colorTemperatureRange: [4000, 12000],
          seed: 100,
        },
        {
          id: 'background',
          count: 4000,
          radiusInner: 400,
          radiusOuter: 600,
          sizeRange: [0.4, 0.9],
          brightnessRange: [0.2, 0.5],
          colorTemperatureRange: [3500, 10000],
          seed: 42,
        },
      ],
      low: [
        {
          id: 'background',
          count: 3000,
          radiusInner: 400,
          radiusOuter: 600,
          sizeRange: [0.4, 0.9],
          brightnessRange: [0.2, 0.5],
          colorTemperatureRange: [3500, 10000],
          seed: 42,
        },
      ],
    },
  },
  minimal: {
    id: 'minimal',
    densityBase: 0.3,
    opacityBase: 0.6,
    sizeBase: 0.6,
    twinkleSpeedBase: 0.3,
    parallaxStrength: 1.0,
    layers: {
      ultra: [
        {
          id: 'background',
          count: 3000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.2, 0.5],
          brightnessRange: [0.1, 0.3],
          colorTemperatureRange: [5000, 9000],
          seed: 42,
        },
      ],
      high: [
        {
          id: 'background',
          count: 2000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.2, 0.5],
          brightnessRange: [0.1, 0.3],
          colorTemperatureRange: [5000, 9000],
          seed: 42,
        },
      ],
      medium: [
        {
          id: 'background',
          count: 1000,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.3, 0.6],
          brightnessRange: [0.1, 0.3],
          colorTemperatureRange: [5000, 9000],
          seed: 42,
        },
      ],
      low: [
        {
          id: 'background',
          count: 500,
          radiusInner: 400,
          radiusOuter: 500,
          sizeRange: [0.3, 0.6],
          brightnessRange: [0.15, 0.35],
          colorTemperatureRange: [5000, 8000],
          seed: 42,
        },
      ],
    },
  },
};
