import type { PlanetManifestEntry } from './planet-manifest';

const EMPTY_TEXTURE = '';

export const PLANET_DEFINITIONS: PlanetManifestEntry[] = [
  {
    id: 'mercury-home',
    name: 'home',
    displayName: 'Home',
    order: 1,
    radius: 1.8,
    colorPalette: ['#8a6d4e', '#3a2f25', '#d4a35d'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#1f1208',
    emissiveIntensity: 0.08,
    rotationSpeed: 0.0017,
    orbitRadius: 28,
    orbitSpeed: 0.078,
    tilt: 0.03,
    cameraDistance: 6.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'home',
    theme: 'cinematic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Home' },
    slug: 'home',
    description: 'Identity, positioning, and first impression.',
    atmosphere: { hasAtmosphere: true, color: '#d8a24a', density: 0.28, glowOpacity: 0.22 },
    ring: { hasRing: false },
    moons: [],
    icon: 'Sun',
    status: 'active',
    physics: {
      velocity: '47.36 km/s',
      rotation: '58.6 Days',
      tilt: '0.03°',
      gravity: '3.7 m/s²',
      type: 'Terrestrial Planet',
    },
  },
  {
    id: 'venus-about',
    name: 'about',
    displayName: 'About',
    order: 2,
    radius: 2.7,
    colorPalette: ['#b88955', '#4a3625', '#e3c18b'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#2b1507',
    emissiveIntensity: 0.1,
    rotationSpeed: -0.0004,
    orbitRadius: 45,
    orbitSpeed: 0.058,
    tilt: 177.3,
    cameraDistance: 8.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'about',
    theme: 'cinematic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'About' },
    slug: 'about',
    description: 'Personal story, principles, and working philosophy.',
    atmosphere: { hasAtmosphere: true, color: '#f0c27b', density: 0.42, glowOpacity: 0.32 },
    ring: { hasRing: false },
    moons: [],
    icon: 'User',
    status: 'active',
    physics: {
      velocity: '35.02 km/s',
      rotation: '243 Days (Retro)',
      tilt: '177.3°',
      gravity: '8.87 m/s²',
      type: 'Terrestrial Planet',
    },
  },
  {
    id: 'earth-projects',
    name: 'projects',
    displayName: 'Projects',
    order: 3,
    radius: 3.1,
    colorPalette: ['#283b3d', '#627c7c', '#c9944a'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#c88735',
    emissiveIntensity: 0.2,
    rotationSpeed: 0.1,
    orbitRadius: 65,
    orbitSpeed: 0.05,
    tilt: 23.4,
    cameraDistance: 9.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'projects',
    theme: 'realistic',
    qualityPreset: 'ultra',
    futureMetadata: { sectionLabel: 'Projects' },
    slug: 'projects',
    description: 'Selected product and engineering case studies.',
    atmosphere: { hasAtmosphere: false, color: '#6a8a98', density: 0.12, glowOpacity: 0.08 },
    ring: { hasRing: false },
    moons: [{ id: 'luna', name: 'Luna', radius: 0.6, orbitRadius: 5.5, orbitSpeed: 0.95 }],
    icon: 'Briefcase',
    status: 'active',
    physics: {
      velocity: '29.78 km/s',
      rotation: '23h 56m',
      tilt: '23.4°',
      gravity: '9.8 m/s²',
      type: 'Terrestrial Planet',
    },
  },
  {
    id: 'mars-services',
    name: 'services',
    displayName: 'Services',
    order: 4,
    radius: 2.4,
    colorPalette: ['#9d4d2c', '#452015', '#d88347'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#2a0e06',
    emissiveIntensity: 0.08,
    rotationSpeed: 0.097,
    orbitRadius: 90,
    orbitSpeed: 0.04,
    tilt: 25.2,
    cameraDistance: 8.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'services',
    theme: 'cinematic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Services' },
    slug: 'services',
    description: 'Premium build, automation, and product engineering offers.',
    atmosphere: { hasAtmosphere: true, color: '#d8873a', density: 0.2, glowOpacity: 0.24 },
    ring: { hasRing: false },
    moons: [
      { id: 'phobos', name: 'Phobos', radius: 0.2, orbitRadius: 4.0, orbitSpeed: 1.35 },
      { id: 'deimos', name: 'Deimos', radius: 0.15, orbitRadius: 5.2, orbitSpeed: 0.82 },
    ],
    icon: 'Rocket',
    status: 'active',
    physics: {
      velocity: '24.07 km/s',
      rotation: '24h 37m',
      tilt: '25.2°',
      gravity: '3.72 m/s²',
      type: 'Terrestrial Planet',
    },
  },
  {
    id: 'jupiter-skills',
    name: 'skills',
    displayName: 'Skills',
    order: 5,
    radius: 5.3,
    colorPalette: ['#b18b63', '#60452f', '#e8c18b'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#24150a',
    emissiveIntensity: 0.06,
    rotationSpeed: 0.24,
    orbitRadius: 140,
    orbitSpeed: 0.021,
    tilt: 3.1,
    cameraDistance: 16.0,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'skills',
    theme: 'realistic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Skills' },
    slug: 'skills',
    description: 'Technical constellations, tools, and craft depth.',
    atmosphere: { hasAtmosphere: true, color: '#e6c08a', density: 0.24, glowOpacity: 0.2 },
    ring: { hasRing: false },
    moons: [
      { id: 'io', name: 'Io', radius: 0.35, orbitRadius: 7.8, orbitSpeed: 1.05 },
      { id: 'europa', name: 'Europa', radius: 0.3, orbitRadius: 9.1, orbitSpeed: 0.78 },
      { id: 'ganymede', name: 'Ganymede', radius: 0.4, orbitRadius: 10.6, orbitSpeed: 0.52 },
    ],
    icon: 'Code2',
    status: 'active',
    physics: {
      velocity: '13.07 km/s',
      rotation: '9h 55m',
      tilt: '3.1°',
      gravity: '24.79 m/s²',
      type: 'Gas Giant',
    },
  },
  {
    id: 'saturn-experience',
    name: 'experience',
    displayName: 'Experience',
    order: 6,
    radius: 4.4,
    colorPalette: ['#c7a470', '#54442f', '#f0d19c'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#201509',
    emissiveIntensity: 0.05,
    rotationSpeed: 0.22,
    orbitRadius: 190,
    orbitSpeed: 0.016,
    tilt: 26.7,
    cameraDistance: 14.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'experience',
    theme: 'realistic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Experience' },
    slug: 'experience',
    description: 'Career timeline, education, and credibility markers.',
    atmosphere: { hasAtmosphere: true, color: '#f0d19c', density: 0.18, glowOpacity: 0.18 },
    ring: { hasRing: true, innerRadius: 5.6, outerRadius: 8.0, color: '#d8b071' },
    moons: [{ id: 'titan', name: 'Titan', radius: 0.45, orbitRadius: 9.5, orbitSpeed: 0.62 }],
    icon: 'Orbit',
    status: 'active',
    physics: {
      velocity: '9.68 km/s',
      rotation: '10h 33m',
      tilt: '26.7°',
      gravity: '10.44 m/s²',
      type: 'Gas Giant',
    },
  },
  {
    id: 'uranus-github',
    name: 'github',
    displayName: 'GitHub',
    order: 7,
    radius: 3.6,
    colorPalette: ['#29465f', '#132432', '#7ea0b6'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#07131d',
    emissiveIntensity: 0.08,
    rotationSpeed: -0.14,
    orbitRadius: 250,
    orbitSpeed: 0.011,
    tilt: 97.8,
    cameraDistance: 11.0,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'github',
    theme: 'cinematic',
    qualityPreset: 'medium',
    futureMetadata: { sectionLabel: 'GitHub' },
    slug: 'github',
    description: 'Open source, hackathons, and live contribution signals.',
    atmosphere: { hasAtmosphere: true, color: '#587a96', density: 0.3, glowOpacity: 0.24 },
    ring: { hasRing: false },
    moons: [{ id: 'titania', name: 'Titania', radius: 0.28, orbitRadius: 6.5, orbitSpeed: 0.48 }],
    icon: 'Github',
    status: 'active',
    physics: {
      velocity: '6.80 km/s',
      rotation: '17h 14m (Retro)',
      tilt: '97.8°',
      gravity: '8.69 m/s²',
      type: 'Ice Giant',
    },
  },
  {
    id: 'neptune-contact',
    name: 'contact',
    displayName: 'Contact',
    order: 8,
    radius: 3.4,
    colorPalette: ['#1e40af', '#172554', '#60a5fa'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#1e3a8a',
    emissiveIntensity: 0.16,
    rotationSpeed: 0.15,
    orbitRadius: 320,
    orbitSpeed: 0.009,
    tilt: 28.3,
    cameraDistance: 10.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'contact',
    theme: 'minimalist',
    qualityPreset: 'medium',
    futureMetadata: { sectionLabel: 'Contact' },
    slug: 'contact',
    description: 'Availability, meeting links, and direct contact.',
    atmosphere: { hasAtmosphere: true, color: '#3b82f6', density: 0.18, glowOpacity: 0.2 },
    ring: { hasRing: false },
    moons: [{ id: 'triton', name: 'Triton', radius: 0.22, orbitRadius: 5.5, orbitSpeed: 0.72 }],
    icon: 'Mail',
    status: 'active',
    physics: {
      velocity: '5.43 km/s',
      rotation: '16h 6m',
      tilt: '28.3°',
      gravity: '11.15 m/s²',
      type: 'Ice Giant',
    },
  },
  {
    id: 'pluto-freelance',
    name: 'freelance',
    displayName: 'Freelance',
    order: 9,
    radius: 1.6,
    colorPalette: ['#14b8a6', '#0f766e', '#5eead4'], // Teal theme for freelance
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#115e59',
    emissiveIntensity: 0.1,
    rotationSpeed: 0.05,
    orbitRadius: 400, // Furthest out
    orbitSpeed: 0.007,
    tilt: 15.0,
    cameraDistance: 5.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'freelance',
    theme: 'cinematic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Freelance' },
    slug: 'freelance',
    description: 'Client work, freelance journey, and delivered projects.',
    atmosphere: { hasAtmosphere: true, color: '#2dd4bf', density: 0.15, glowOpacity: 0.2 },
    ring: { hasRing: false },
    moons: [],
    icon: 'Briefcase',
    status: 'active',
    physics: {
      velocity: '4.74 km/s',
      rotation: '6.4 Days',
      tilt: '122.5°',
      gravity: '0.62 m/s²',
      type: 'Dwarf Planet',
    },
  },
];
export default PLANET_DEFINITIONS;

