import type { PlanetManifestEntry } from './planet-manifest';

const EMPTY_TEXTURE = '';

export const PLANET_DEFINITIONS: PlanetManifestEntry[] = [
  {
    id: 'mercury-home',
    name: 'home',
    displayName: 'Home',
    order: 1,
    radius: 0.72,
    colorPalette: ['#8a6d4e', '#3a2f25', '#d4a35d'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#1f1208',
    emissiveIntensity: 0.08,
    rotationSpeed: 0.02,
    orbitRadius: 9,
    orbitSpeed: 0.092,
    tilt: 3,
    cameraDistance: 4,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'home',
    theme: 'cinematic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Home' },
    slug: 'home',
    description: 'Identity, positioning, and first impression.',
    atmosphere: { hasAtmosphere: true, color: '#d8a24a', density: 0.28, glowOpacity: 0.22 },
    ring: { hasRing: false },
    moons: [],
    icon: 'Sun',
    status: 'active',
  },
  {
    id: 'venus-about',
    name: 'about',
    displayName: 'About',
    order: 2,
    radius: 1.08,
    colorPalette: ['#b88955', '#4a3625', '#e3c18b'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#2b1507',
    emissiveIntensity: 0.1,
    rotationSpeed: -0.01,
    orbitRadius: 13.5,
    orbitSpeed: 0.068,
    tilt: 177,
    cameraDistance: 5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'about',
    theme: 'cinematic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'About' },
    slug: 'about',
    description: 'Personal story, principles, and working philosophy.',
    atmosphere: { hasAtmosphere: true, color: '#f0c27b', density: 0.42, glowOpacity: 0.32 },
    ring: { hasRing: false },
    moons: [],
    icon: 'User',
    status: 'active',
  },
  {
    id: 'earth-projects',
    name: 'projects',
    displayName: 'Projects',
    order: 3,
    radius: 1.22,
    colorPalette: ['#283b3d', '#627c7c', '#c9944a'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#c88735',
    emissiveIntensity: 0.2,
    rotationSpeed: 0.1,
    orbitRadius: 18.5,
    orbitSpeed: 0.052,
    tilt: 23.5,
    cameraDistance: 5.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'projects',
    theme: 'realistic',
    qualityPreset: 'ultra',
    futureMetadata: { sectionLabel: 'Projects' },
    slug: 'projects',
    description: 'Selected product and engineering case studies.',
    atmosphere: { hasAtmosphere: false, color: '#6a8a98', density: 0.12, glowOpacity: 0.08 },
    ring: { hasRing: false },
    moons: [{ id: 'luna', name: 'Luna', radius: 0.24, orbitRadius: 2.35, orbitSpeed: 0.95 }],
    icon: 'Briefcase',
    status: 'active',
  },
  {
    id: 'mars-services',
    name: 'services',
    displayName: 'Services',
    order: 4,
    radius: 0.96,
    colorPalette: ['#9d4d2c', '#452015', '#d88347'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#2a0e06',
    emissiveIntensity: 0.08,
    rotationSpeed: 0.12,
    orbitRadius: 24.5,
    orbitSpeed: 0.041,
    tilt: 25,
    cameraDistance: 4.8,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'services',
    theme: 'cinematic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Services' },
    slug: 'services',
    description: 'Premium build, automation, and product engineering offers.',
    atmosphere: { hasAtmosphere: true, color: '#d8873a', density: 0.2, glowOpacity: 0.24 },
    ring: { hasRing: false },
    moons: [
      { id: 'phobos', name: 'Phobos', radius: 0.08, orbitRadius: 1.55, orbitSpeed: 1.35 },
      { id: 'deimos', name: 'Deimos', radius: 0.06, orbitRadius: 2.05, orbitSpeed: 0.82 },
    ],
    icon: 'Rocket',
    status: 'active',
  },
  {
    id: 'jupiter-skills',
    name: 'skills',
    displayName: 'Skills',
    order: 5,
    radius: 2.1,
    colorPalette: ['#b18b63', '#60452f', '#e8c18b'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#24150a',
    emissiveIntensity: 0.06,
    rotationSpeed: 0.3,
    orbitRadius: 33,
    orbitSpeed: 0.028,
    tilt: 3,
    cameraDistance: 8,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'skills',
    theme: 'realistic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Skills' },
    slug: 'skills',
    description: 'Technical constellations, tools, and craft depth.',
    atmosphere: { hasAtmosphere: true, color: '#e6c08a', density: 0.24, glowOpacity: 0.2 },
    ring: { hasRing: false },
    moons: [
      { id: 'io', name: 'Io', radius: 0.14, orbitRadius: 3.1, orbitSpeed: 1.05 },
      { id: 'europa', name: 'Europa', radius: 0.12, orbitRadius: 3.65, orbitSpeed: 0.78 },
      { id: 'ganymede', name: 'Ganymede', radius: 0.16, orbitRadius: 4.25, orbitSpeed: 0.52 },
    ],
    icon: 'Code2',
    status: 'active',
  },
  {
    id: 'saturn-experience',
    name: 'experience',
    displayName: 'Experience',
    order: 6,
    radius: 1.75,
    colorPalette: ['#c7a470', '#54442f', '#f0d19c'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#201509',
    emissiveIntensity: 0.05,
    rotationSpeed: 0.25,
    orbitRadius: 42,
    orbitSpeed: 0.019,
    tilt: 27,
    cameraDistance: 8,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'experience',
    theme: 'realistic',
    qualityPreset: 'high',
    futureMetadata: { sectionLabel: 'Experience' },
    slug: 'experience',
    description: 'Career timeline, education, and credibility markers.',
    atmosphere: { hasAtmosphere: true, color: '#f0d19c', density: 0.18, glowOpacity: 0.18 },
    ring: { hasRing: true, innerRadius: 2.25, outerRadius: 3.2, color: '#d8b071' },
    moons: [{ id: 'titan', name: 'Titan', radius: 0.18, orbitRadius: 3.8, orbitSpeed: 0.62 }],
    icon: 'Orbit',
    status: 'active',
  },
  {
    id: 'neptune-github',
    name: 'github',
    displayName: 'GitHub',
    order: 7,
    radius: 1.45,
    colorPalette: ['#29465f', '#132432', '#7ea0b6'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#07131d',
    emissiveIntensity: 0.08,
    rotationSpeed: 0.15,
    orbitRadius: 52,
    orbitSpeed: 0.013,
    tilt: 29,
    cameraDistance: 6.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'github',
    theme: 'cinematic',
    qualityPreset: 'medium',
    futureMetadata: { sectionLabel: 'GitHub' },
    slug: 'github',
    description: 'Open source, hackathons, and live contribution signals.',
    atmosphere: { hasAtmosphere: true, color: '#587a96', density: 0.3, glowOpacity: 0.24 },
    ring: { hasRing: false },
    moons: [{ id: 'triton', name: 'Triton', radius: 0.11, orbitRadius: 2.6, orbitSpeed: 0.48 }],
    icon: 'Github',
    status: 'active',
  },
  {
    id: 'pluto-contact',
    name: 'contact',
    displayName: 'Contact',
    order: 8,
    radius: 0.58,
    colorPalette: ['#6f756f', '#222624', '#d7c4a6'],
    texture: EMPTY_TEXTURE,
    normalMap: EMPTY_TEXTURE,
    roughnessMap: EMPTY_TEXTURE,
    emissive: '#d8a24a',
    emissiveIntensity: 0.16,
    rotationSpeed: 0.03,
    orbitRadius: 61,
    orbitSpeed: 0.009,
    tilt: 17,
    cameraDistance: 3.5,
    cameraTarget: [0, 0, 0],
    portfolioSection: 'contact',
    theme: 'minimalist',
    qualityPreset: 'medium',
    futureMetadata: { sectionLabel: 'Contact' },
    slug: 'contact',
    description: 'Availability, meeting links, and direct contact.',
    atmosphere: { hasAtmosphere: true, color: '#d8a24a', density: 0.18, glowOpacity: 0.2 },
    ring: { hasRing: false },
    moons: [{ id: 'charon', name: 'Charon', radius: 0.09, orbitRadius: 1.25, orbitSpeed: 0.72 }],
    icon: 'Mail',
    status: 'active',
  },
];
export default PLANET_DEFINITIONS;
