import type { QualityTier } from '@/lib/store';
import type { SunPresetConfig } from './sun-types';

export const SUN_PRESETS: Record<QualityTier, SunPresetConfig> = {
  ultra: {
    radius: 5.4,
    coreColor: '#ff5800',
    glowColor: '#ffc040',
    flareColor: '#ff8820',
    emissiveIntensity: 0.95,
    glowScale: 1.18,
    glowOpacity: 0.26,
    coronaScale: 1.36,
    coronaOpacity: 0.12,
    coronaSpeed: 0.022,
    enableGlow: true,
    enableCorona: true,
    enableFlares: false,
    octaves: 4,
  },
  high: {
    radius: 5.15,
    coreColor: '#ff5800',
    glowColor: '#ffc040',
    flareColor: '#ff8820',
    emissiveIntensity: 0.88,
    glowScale: 1.14,
    glowOpacity: 0.22,
    coronaScale: 1.32,
    coronaOpacity: 0.1,
    coronaSpeed: 0.02,
    enableGlow: true,
    enableCorona: true,
    enableFlares: false,
    octaves: 3,
  },
  medium: {
    radius: 4.9,
    coreColor: '#ff5800',
    glowColor: '#ffc040',
    flareColor: '#ff8820',
    emissiveIntensity: 0.78,
    glowScale: 1.08,
    glowOpacity: 0.2,
    coronaScale: 1.28,
    coronaOpacity: 0.1,
    coronaSpeed: 0.028,
    enableGlow: true,
    enableCorona: true,
    enableFlares: false,
    octaves: 2,
  },
  low: {
    radius: 4.5,
    coreColor: '#ff5800',
    glowColor: '#ffc040',
    flareColor: '#ff8820',
    emissiveIntensity: 0.85,
    glowScale: 1.1,
    glowOpacity: 0.22,
    coronaScale: 1.28,
    coronaOpacity: 0.0,
    coronaSpeed: 0.0,
    enableGlow: true,
    enableCorona: false,
    enableFlares: false,
    octaves: 1,
  },
};
export default SUN_PRESETS;

